<script setup>
defineProps({outcomes:{type:Array,default:()=>[]},variant:{type:String,default:'stacked'},theme:{type:String,default:'light'}});
const pct=(item)=>Number(item.pct ?? item.probability ?? 0);
</script>
<template><div class="probability" :class="[`probability--${variant}`,`probability--${theme}`]">
  <template v-if="variant==='split'"><div v-for="(o,i) in outcomes" :key="o.id||o.label" :class="`tone-${i%3}`"><span>{{ o.label }}</span><b>{{ pct(o).toFixed(1) }}%</b><i><em :style="{width:`${pct(o)}%`}"></em></i></div></template>
  <template v-else><div class="bar"><i v-for="(o,i) in outcomes" :key="o.id||o.label" :class="`tone-${i%3}`" :style="{width:`${pct(o)}%`}"></i></div><div v-for="(o,i) in outcomes" :key="o.id||o.label" class="legend"><span><i :class="`tone-${i%3}`"></i>{{ o.label }}</span><b>{{ pct(o).toFixed(1) }}%</b></div></template>
</div></template>
<style scoped>.probability{font-family:var(--ec-font-body)}.probability--split{display:grid;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));gap:8px}.probability--split>div{padding:11px 12px;border-radius:var(--ec-r-field);background:var(--ec-inset)}.probability--split span,.probability--split b{display:block}.probability--split b{font:700 24px var(--ec-font-display);margin:3px 0}.probability--split i,.bar{display:block;height:5px;background:var(--ec-line);overflow:hidden}.probability--split em{display:block;height:100%;background:var(--ec-orange)}.probability--split .tone-1 em{background:var(--ec-amber)}.probability--split .tone-2 em{background:var(--ec-clay)}.bar{display:flex;margin-bottom:8px}.bar>i{height:100%;background:var(--ec-orange)}.bar>.tone-1{background:var(--ec-amber)}.bar>.tone-2{background:var(--ec-clay)}.legend{display:flex;justify-content:space-between;align-items:center;padding:3px 0;font-size:11px}.legend span{display:flex;align-items:center;gap:6px}.legend span i{width:7px;height:7px;background:var(--ec-orange)}.legend span i.tone-1{background:var(--ec-amber)}.legend span i.tone-2{background:var(--ec-clay)}.legend b{font:700 12px var(--ec-font-mono);color:var(--ec-red)}</style>
